### ISSUE TITLE
Incentive for node provider

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#11]
If you provide a node as localhost or as remote provider for a wallet (like Phoenix) for example you should get a reward for every transaction which is created via your node.

**Proposal**:
 If a tx is genereated with the node the account from the node is included into the transaction as an extra field. When the transaction gets added to a blokck, X% (to discuss) of the fee is going to the node account owner- instead to the miner. 
The logic will be added to the node and needs a HF.

As a side effect - we will see a lot more local nodes used by people (for own discount on the fee) and also a benefit for node provider to be used by Phoenix or BTDEX for example.

**Comment by damccull** [comment]
I like the idea. I don't think it should outweigh the miners share but it needs to be high enough to incentivize the node runners and not just be ridiculous. Maybe 25-33%?

**Comment by maxbrito500** [comment]
Looking at the popularity of lightning for BTC, having a similar mechanism on Signum would be fantastic. It does provide motivation for keeping a good node.

How is the node selection done? For BTC there is a bidding between providers for the lowest fees.

If no bidding occurs, how about a smart contract where the active nodes from the previous 24 hours somehow get a percentage of fees like in a mining pool?

Of course adding measures that prevent someone launching hundreds of fake ghost nodes.

Maybe if possible to create geo-localized rewards, where for example the node providers within a continent share the rewards for transactions performed there.

This would motivate node providers to make them available in a more disperse manner across the globe, along with promoting adoption locally.

**Comment by ohager** [comment]
`If no bidding occurs, how about a smart contract where the active nodes from the previous 24 hours somehow get a percentage of fees like in a mining pool?` - this would require some oracle mechanism...not impossible. Keep in mind that SCs cannot interact with the outer world. The information must somehow inbound.

**Comment by frankTheTank72** [comment]
Added a new ticket https://github.com/signum-network/business-epics/issues/13

**Comment by jjos2372** [comment]
Closing as it will be addressed at #13
