### ISSUE TITLE
Introduce transferable ownership for smart tokens

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#14]
With the goal to have more and more use-cases and business-cases on the chain, we should also support the buy-out/transfer of a business to a new owner.

As the current setup a token and his corresponding transaction, like minting, set Treasury-Account is bind to the creator account.
As the passphrase can´t be changed, we should introduce a new transaction **TransferAssetOwnership**.
With this the current owner (which is by creation = creator) can enable another account to be the new owner.
After the transaction is added to the chain, the smart token owner will change to the new owner, and only this owner can do the following:

- Mint token
- Set Treasury-Accounts
- Set new Owner

The minted tokens will always add to the current owner account on the token.

**Comment by frankTheTank72** [comment]
see https://github.com/signum-network/business-epics/issues/15

**Comment by map1336** [comment]
We can close this issue after a stable release of [Signum Node v3.6.1](https://github.com/signum-network/signum-node/releases/tag/v3.6.1-beta4)

**Comment by map1336** [comment]
Closing this tickets, As this feature has been implemented
https://github.com/signum-network/signum-node/releases/tag/v3.7.0
