### ISSUE TITLE
Develop SIP-43 Token owner

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#15]
https://github.com/signum-network/SIPs/blob/master/SIP/sip-43.md

**Comment by map1336** [comment]
As stated on SIPs repo, SIP 43 has been implemented
https://github.com/signum-network/SIPs/blob/master/SIP/sip-43.md
![image](https://github.com/signum-network/business-epics/assets/35440957/bf12115a-1fc4-4e2c-964e-b7d680148521)
