### ISSUE TITLE
Lending Signa 

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#6]
**Description**
A user should be able to borrow Signa coins for his mining activities.
Both sides miner or holder should be able to create an offer to lend or borrow Signa coins.
A offer will be set by:

- Amount of coins
- Number of blocks for the lend/borrow
- Lending-Fee which would be paid

We would have the following new transaction types:

- Place a lending offer
- Place a borrow offer
- Cancel a lending offer
- Cancel a borrow offer
- Take a lending offer
- Take a borrow offer

The coins from the lender will never leave his wallet.
When an lending offer is created the coins get locked on the lender wallet until the offer is cancelled or the offer is taken and the lending time is reached. The lending-fee is paid upfront to the lender.

A miner which took an offer has the following limitation to get the borrowed coins added virtually to his commitment:

- 10k borrowed coins regardless of the commitment can be added to the virtual commitment
- Only in a ratio 1:3 can be the virtual commitment be added in relation to the own commitment.

( Example if the miner has 500k committed - he can add another 1M coins via borrow)

**Comment by shefass** [comment]
Great idea! There was something similar (without market part) in NXT (NXT -> Burst -> Signum).

It will help to lower amounts kept in CEX'es. From my view it one of main problems of crypto space.

**Comment by Nivok-Spilkommen** [comment]
Could we e more flexible on this point? 'Only in a ratio 1:3 can be the virtual commitment be added in relation to the own commitment.'  I would like to be in a position to lend to somebody with no commitment, maybe put in the ratio once there is 5k committed on the account.

**Comment by frankTheTank72** [comment]
> Could we e more flexible on this point? 'Only in a ratio 1:3 can be the virtual commitment be added in relation to the own commitment.' I would like to be in a position to lend to somebody with no commitment, maybe put in the ratio once there is 5k committed on the account.

i think than this would be valid "10k borrowed coins regardless of the commitment can be added to the virtual commitment"

**Comment by xDWart** [comment]
Are you considering adding mining capabilities to smart contracts?

**Comment by paulpoco** [comment]
I know I would like to see a new commitment transfer function that would send commitment from 1 miner address to a 2nd miner address.  All without having to wait 4 days.

Example:

miner1 address has 37TiB and 750,000 commitment
miner2 address has 1.7TiB and 250,000 commitment 

Then miner2 address sends 50,000 existing commitment to miner1 and nobody waits 4 days.

miner1 also runs into a different problem if they want to remove commitment, they happen to get blocks everyday.   They want remove 250,000 commitment but don't want to stop mining.  What about yes you still wait 4 days but the 250,000 commitment is removed right away and it held for 4 days then released.   So the miner can keep mining just goes down to 500,000 commitment right away & the 250,000 is released in 4 days.

**Comment by frankTheTank72** [comment]
A new version is made with https://github.com/signum-network/business-epics/issues/17, and this proposal  is closed
