### ISSUE TITLE
Use the full block size - independent from the fee

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#8]
The  chain should be able to fill the blocks by the given transactions sorted by the fee ( high first - low last)
In this case we would avoiding that transactions like reward assignment with the current min fee are waiting many blocks beside it could be direct transmitted as the block is not fully used.

The minimum fee should be calcualed by minFee = FEE_QUANT * (transactionBytes / 176)
This would lead to the following :

- Ordinary TX send: 176 bytes, pays FEE_QUANT
- Add commitment: 184 bytes, pays FEE_QUANT
- Deposit to Bittrex (with the memo): 245 bytes, pays FEE_QUANT
- Place token order: 201 bytes, pays FEE_QUANT
- TX send to extended address (with public key attached): 209 bytes, pays FEE_QUANT
- Multi-out with the max receivers: over 1200 bytes, pays 6*FEE_QUANT 
- Message with max attachment: over 1200 bytes, pays 6*FEE_QUANT 
- Create subscription: 181 bytes, pays FEE_QUANT

For the following transaction types we would add a higher multiplyer with the minFee:

Type | Value | Subtype | Value | min-Fee-Factor | Max payment
-- | -- | -- | -- | -- | --
Messaging |  1 | Alias Assignment | 1 | 20x | 120x
Colored coins | 2 | Asset Issuance | 0 | 15000x | 110.25 SIGNA

**Comment by ohager** [comment]
According to your example the exact formula would be: `minFee = FEE_QUANT * Math.floor(txByteLength/176)`  with _FEE_QUANT=0.00735 SIGNA_

**Comment by frankTheTank72** [comment]
See https://github.com/signum-network/CIPs/blob/master/cip-0031.md
