### ISSUE TITLE
API and Hash-table for SmartContracts 

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/business-epics#9]
**Description**
If you start to create smart contracts for an application on the chain you can either go the way that the smart contracts are only issued by your account and you handover the ownership within the smart contract to ensure the correct code.

Another way could be that you want to ensure that only smart contract with your original code is taken into your application.
To be able to proof this every smart contract will get a hash for his machine-code on the node (created by the node with a given function). 

Now a user can verify via a new API call if the smart contract XYZ is with the same execution code he wants by just comparing the hashes (his original hash and hash from the SC on the chain)

**Implementation Details**
To enable scripts and user to proof SCs we need the following items:

- New table entry with the hash on the Node-DB
- Function for the Node to create the hash
- API call to get a hash for a single SC
- API call to get all SC with a given hash
- API call to handover machine-code and get the hash

All exisitng SCs need tio get a hash entry when the node starts the first time

**Comment by frankTheTank72** [comment]
see https://github.com/signum-network/CIPs/blob/master/cip-0030.md

**Comment by jjos2372** [comment]
The only thing missing is the "API call to handover machine-code and get the hash", maybe we don't need that for our use cases. If so, we can close this.
